services:
  app:
    build: .
    container_name: json-storage
    environment:
      POSTGRES_DSN: postgresql://json:json@postgres:5432/jsonstorage
      ELASTICSEARCH_URL: http://elastic-data:9200
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elastic-data
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: jsonstorage
      POSTGRES_USER: json
      POSTGRES_PASSWORD: json
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elastic-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elastic-data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=es-data
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  prometheus:
    build: ./prometheus
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  pgdata:
  esdata:
  grafana-data:
